FROM node:latest as build-stage
WORKDIR /app

# Copy the package.json and package-lock.json (or yarn.lock) files
ENV PATH /app/node_modules/.bin:$PATH
COPY ./songuess-fe/package.json ./songuess-fe/package-lock.json ./
COPY ./songuess-fe/src ./src
COPY ./songuess-fe/public ./public
RUN npm install

# Build the project for production
RUN npm run build

FROM nginx:stable-alpine as serve-stage

COPY --from=build-stage /app/build /usr/share/nginx/html

EXPOSE 80